/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreateDeployModal: typeof import('./src/components/CreateDeployModal.vue')['default']
    CreateImage: typeof import('./src/components/CreateImage.vue')['default']
    ExposeDeployModal: typeof import('./src/components/ExposeDeployModal.vue')['default']
    GlobalContent: typeof import('./src/components/GlobalContent.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    ModifyImage: typeof import('./src/components/ModifyImage.vue')['default']
    MutateService: typeof import('./src/components/MutateService.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCreateImage: typeof import('./src/components/SimpleCreateImage.vue')['default']
    SimpleCreatePod: typeof import('./src/components/SimpleCreatePod.vue')['default']
    TableHeader: typeof import('./src/components/TableHeader.vue')['default']
    UpdateDeployModal: typeof import('./src/components/UpdateDeployModal.vue')['default']
  }
}
